name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Release]
        bundled: [true]
        include:
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build tasync.csproj -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} --output release-${{ matrix.os }}
    - name: Release on ${{ matrix.os }} 
      uses: actions/upload-artifact@v4
      with:
        name: "Release ${{matrix.os}}"
        path: "release-${{matrix.os}}"
    - name: Release
      uses: softprops/action-gh-release@v2.0.4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: release-${{matrix.os}}
        name: Release-${{matrix.os}}
        prerelease: false
        files: "release-${{matrix.os}}/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

