name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Release]
        bundled: [true]
        include:
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build tasync.csproj -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} --output release-${{ matrix.os }}
    - uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: release-${{ matrix.os }}.zip
        path: release-${{ matrix.os }}
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: release-${{ matrix.os }}.zip
        tag_name: rel-${{ github.run_number }}
        name: Release ${{ github.run_number }}
        



