name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Release]
        bundled: [true]
        include:
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build tasync.csproj -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} --output release-${{ matrix.os }}
    - name: Release on ${{ matrix.os }} 
      uses: actions/upload-artifact@v4
      with:
        name: "Release ${{matrix.os}}"
        path: "release-${{matrix.os}}"
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: action/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag-name: release
          name: Release
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            */*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

